namespace AniSharp.Types.Users
{
	public enum UserTitleLanguage
	{
		ROMAJI,
		ENGLISH,
		NATIVE,
		ROMAJI_STYLISED,
		ENGLISH_STYLISED,
		NATIVE_STYLISED,
	}

	public enum NotificationType
	{
		ACTIVITY_MESSAGE,
		ACTIVITY_REPLY,
		FOLLOWING,
		ACTIVITY_MENTION,
		THREAD_COMMENT_MENTION,
		THREAD_SUBSCRIBED,
		THREAD_COMMENT_REPLY,
		AIRING,
		ACTIVITY_LIKE,
		ACTIVITY_REPLY_LIKE,
		THREAD_LIKE,
		THREAD_COMMENT_LIKE,
		ACTIVITY_REPLY_SUBSCRIBED,
		RELATED_MEDIA_ADDITION,
	}

	public enum ScoreFormat
	{
		POINT_100,
		POINT_10_DECIMAL,
		POINT_10,
		POINT_5,
		POINT_3,
	}

	public enum UserSort
	{
		ID,
		ID_DESC,
		USERNAME,
		USERNAME_DESC,
		WATCHED_TIME,
		WATCHED_TIME_DESC,
		CHAPTERS_READ,
		CHAPTERS_READ_DESC,
		SEARCH_MATCH,
	}
}